# Generated by Django 4.1.7 on 2023-02-28 16:46

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_number", models.CharField(max_length=200)),
                (
                    "account_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "account_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_type",
                    models.IntegerField(
                        choices=[(0, "Expense"), (1, "Income")], default=0
                    ),
                ),
                ("category_name", models.CharField(default="None", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.IntegerField(
                        choices=[(0, "Expense"), (1, "Income")], default=0
                    ),
                ),
                (
                    "transaction_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "transaction_sum",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("transaction_comment", models.CharField(max_length=255)),
                (
                    "transaction_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hb_api_app.account",
                    ),
                ),
                (
                    "transaction_category",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="hb_api_app.transactioncategory",
                    ),
                ),
            ],
        ),
    ]
