# Generated by Django 4.1.7 on 2023-03-01 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hb_api_app", "0002_planingtransaction"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PlaningTransaction", new_name="PlanningTransaction",
        ),
    ]
